model:
  name: Diffusion
  module: models.diffusion
  n_layers: 4
  input_dim: 4
  n_hidden: 64
  act: 'gelu'
  n_head: 8
  mlp_ratio: 4.0
  out_dim: 4
  dropout: 0.0
  seq_length: 21
  beta_min: 0.0001
  beta_max: 0.02
  timesteps: 1000

